from __future__ import annotations

from pathlib import Path
import csv
import json
import math
import zipfile
from .model import ensure_dir, write_json


def export_signalk(root: Path) -> Path:
    seamarks = json.loads((root / "raw" / "openseamap" / "seamarks.geojson").read_text(encoding="utf-8"))
    resources = {"resources": {"notes": {}, "regions": {}, "waypoints": {}}}
    for f in seamarks["features"]:
        lon, lat = f["geometry"]["coordinates"]
        props = f["properties"]
        resources["resources"]["waypoints"][props["id"]] = {
            "name": props.get("name", props["id"]),
            "position": {"longitude": lon, "latitude": lat},
            "type": props.get("kind"),
            "description": "Prototype object exported for Signal K ecosystem compatibility.",
        }
    return write_json(root / "offline_bundle" / "signalk" / "resources.json", resources)


def export_opencpn_layers(root: Path) -> list[Path]:
    out = ensure_dir(root / "offline_bundle" / "opencpn")
    files = []
    for rel in ["raw/openseamap/seamarks.geojson", "intermediate/derived/depth_contours.geojson", "intermediate/derived/anchorages.geojson"]:
        src = root / rel
        dst = out / src.name
        dst.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
        files.append(dst)
    readme = out / "README_OpenCPN.txt"
    readme.write_text(
        "Prototype OpenCPN offline layer package. Load GeoJSON layers as supplemental data. "
        "Production exporters should create S-57/KAP/MBTiles bundles. Not for navigation.\n",
        encoding="utf-8",
    )
    files.append(readme)
    return files


def _load_bathy(root: Path):
    rows = list(csv.DictReader((root / "raw" / "copernicus" / "bathymetry_grid.csv").open(encoding="utf-8")))
    lons = sorted({float(r["lon"]) for r in rows})
    lats = sorted({float(r["lat"]) for r in rows})
    grid = {(float(r["lon"]), float(r["lat"])): float(r["depth_m"]) for r in rows}
    return rows, lons, lats, grid


def export_svg_figure(root: Path) -> Path:
    bathy, lons, lats, _ = _load_bathy(root)
    seamarks = json.loads((root / "raw" / "openseamap" / "seamarks.geojson").read_text(encoding="utf-8"))["features"]
    depths = [float(r["depth_m"]) for r in bathy]
    west, east, south, north = min(lons), max(lons), min(lats), max(lats)
    width, height = 1000, 900

    def xy(lon: float, lat: float) -> tuple[float, float]:
        x = 70 + (lon - west) / (east - west) * 850
        y = 790 - (lat - south) / (north - south) * 700
        return x, y

    min_d, max_d = min(depths), max(depths)
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">']
    parts.append('<rect width="100%" height="100%" fill="white"/>')
    parts.append('<text x="70" y="38" font-size="24" font-family="serif">Tyrrhenian Open Nautical Atlas - Prototype bathymetry and seamarks</text>')
    parts.append('<text x="70" y="65" font-size="13" font-family="serif">Generated by euroopencharts example workflow. Experimental: not for navigation.</text>')
    for r in bathy[::2]:
        lon, lat, d = float(r["lon"]), float(r["lat"]), float(r["depth_m"])
        x, y = xy(lon, lat)
        shade = int(235 - 155 * (d - min_d) / (max_d - min_d))
        parts.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="3.3" fill="rgb({shade},{shade},{255})" opacity="0.75"/>')
    for f in seamarks:
        lon, lat = f["geometry"]["coordinates"]
        x, y = xy(lon, lat)
        kind = f["properties"].get("kind", "object")
        symbol = {"light": "L", "buoy": "B", "harbor": "H", "marina": "M", "anchorage": "A", "poi": "P"}.get(kind, "O")
        parts.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="10" fill="none" stroke="black" stroke-width="1.2"/>')
        parts.append(f'<text x="{x-4:.1f}" y="{y+4:.1f}" font-size="11" font-family="sans-serif">{symbol}</text>')
    parts.append('<rect x="70" y="90" width="850" height="700" fill="none" stroke="black"/>')
    parts.append('<text x="760" y="828" font-size="12" font-family="serif">CRS: EPSG:4326 | Output: SVG paper-ready vector figure</text>')
    parts.append('</svg>')
    out = ensure_dir(root / "figures") / "prototype_bathymetry_seamarks.svg"
    out.write_text("\n".join(parts), encoding="utf-8")
    return out


def export_chart_rendering(root: Path) -> list[Path]:
    """Render a copyright-safe nautical-style PNG/PDF from generated products.

    The design uses only generic hydrographic conventions: yellow land, white sea,
    gray contours, magenta cell frames, red dashed notices, and simple custom
    symbols. It deliberately avoids proprietary brand marks, icons, fonts, and
    copyrighted tile artwork.
    """
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        from matplotlib.patches import Polygon, Rectangle
        import matplotlib.patheffects as pe
        import numpy as np
    except Exception as exc:  # pragma: no cover - gives unattended users a clear error
        raise RuntimeError("export_chart_rendering requires matplotlib and numpy") from exc

    bathy, lons, lats, grid = _load_bathy(root)
    seamarks = json.loads((root / "raw" / "openseamap" / "seamarks.geojson").read_text(encoding="utf-8"))["features"]
    anchorages = json.loads((root / "intermediate" / "derived" / "anchorages.geojson").read_text(encoding="utf-8"))["features"]
    lon_index = {v: i for i, v in enumerate(lons)}
    lat_index = {v: i for i, v in enumerate(lats)}
    z = np.zeros((len(lats), len(lons)))
    for r in bathy:
        z[lat_index[float(r["lat"])]][lon_index[float(r["lon"] )]] = float(r["depth_m"])
    x, y = np.meshgrid(lons, lats)

    xmin, xmax = 13.65, 14.75
    ymin, ymax = 40.48, 41.02

    mainland = np.array([
        [13.97, 41.02], [14.75, 41.02], [14.75, 40.73], [14.67, 40.72],
        [14.60, 40.70], [14.55, 40.66], [14.50, 40.63], [14.44, 40.61],
        [14.38, 40.61], [14.33, 40.63], [14.29, 40.66], [14.24, 40.69],
        [14.18, 40.72], [14.12, 40.76], [14.08, 40.80], [14.04, 40.84],
        [13.99, 40.88], [13.94, 40.91], [13.91, 40.96], [13.97, 41.02]
    ])
    capri = np.array([[14.18,40.54], [14.26,40.535], [14.31,40.555], [14.30,40.585], [14.24,40.600], [14.18,40.590], [14.15,40.565], [14.18,40.54]])
    ischia = np.array([[13.82,40.69], [13.94,40.69], [13.99,40.725], [13.98,40.785], [13.91,40.825], [13.82,40.805], [13.77,40.765], [13.76,40.72], [13.82,40.69]])
    procida = np.array([[14.00,40.745], [14.045,40.745], [14.065,40.765], [14.052,40.79], [14.01,40.795], [13.99,40.772], [14.00,40.745]])

    def text_outline(ax, *args, **kwargs):
        kwargs.setdefault("path_effects", [pe.withStroke(linewidth=2.5, foreground="white")])
        return ax.text(*args, **kwargs)

    def draw_pin(ax, xx, yy, label=""):
        ax.scatter([xx], [yy], s=360, marker="o", facecolor="#0b62a3", edgecolor="white", linewidth=2.2, zorder=9)
        ax.text(xx, yy, "A", ha="center", va="center", fontsize=13, color="white", weight="bold", zorder=10)
        if label:
            text_outline(ax, xx + 0.014, yy + 0.012, label, fontsize=8, zorder=11)

    def draw_lighthouse(ax, xx, yy):
        ax.add_patch(Rectangle((xx-0.006, yy-0.018), 0.012, 0.032, facecolor="white", edgecolor="black", lw=1.0, zorder=8))
        ax.add_patch(Rectangle((xx-0.004, yy-0.006), 0.008, 0.008, facecolor="red", edgecolor="none", zorder=9))
        ax.plot([xx-0.012, xx+0.012], [yy+0.016, yy+0.016], color="black", lw=1, zorder=8)
        ax.scatter([xx], [yy+0.022], marker="*", s=45, facecolor="yellow", edgecolor="black", zorder=10)

    def draw_buoy(ax, xx, yy):
        ax.plot([xx, xx], [yy-0.016, yy+0.016], color="orangered", lw=1.1, zorder=8)
        ax.plot([xx-0.008, xx+0.008], [yy+0.008, yy+0.008], color="orangered", lw=1.1, zorder=8)
        ax.plot([xx-0.008, xx+0.008], [yy-0.008, yy-0.008], color="orangered", lw=1.1, zorder=8)

    def draw_harbor(ax, xx, yy, name, marina=False):
        ax.scatter([xx], [yy], marker="D" if marina else "s", s=58, facecolor="white", edgecolor="black", zorder=9)
        text_outline(ax, xx+0.012, yy+0.006, name, fontsize=8, zorder=10)

    fig, ax = plt.subplots(figsize=(16, 8.4))
    fig.patch.set_facecolor("white")
    ax.set_facecolor("white")

    for x0 in np.arange(13.65, 14.75, 0.33):
        ax.plot([x0, x0], [ymin, ymax], color="magenta", lw=0.9, zorder=1)
    for y0 in np.arange(40.50, 41.02, 0.16):
        ax.plot([xmin, xmax], [y0, y0], color="magenta", lw=0.9, zorder=1)
    for x0, y0, w, h in [(13.80,40.70,0.34,0.27),(14.25,40.56,0.42,0.18),(13.96,40.84,0.32,0.16),(14.52,40.64,0.25,0.17)]:
        ax.add_patch(Rectangle((x0,y0), w, h, fill=False, edgecolor="magenta", linewidth=1.0, zorder=1))

    cs = ax.contour(x, y, z, levels=[20, 50, 100, 200, 500, 750, 1000, 1250, 1500], colors="0.35", linewidths=0.65, zorder=2)
    ax.clabel(cs, levels=[50,100,200,500,1000], inline=True, fontsize=8, fmt="%d")

    for p in [
        np.array([[13.78,40.70],[13.95,40.69],[14.02,40.75],[13.95,40.83],[13.79,40.81],[13.73,40.75],[13.78,40.70]]),
        np.array([[14.17,40.58],[14.33,40.56],[14.42,40.61],[14.37,40.70],[14.22,40.68],[14.14,40.63],[14.17,40.58]]),
        np.array([[14.02,40.79],[14.20,40.80],[14.23,40.91],[14.10,40.96],[13.98,40.90],[14.02,40.79]])
    ]:
        ax.plot(p[:,0], p[:,1], color="orangered", lw=1.0, linestyle=(0,(5,4)), zorder=3)
    for xx in np.linspace(13.75,14.35,9):
        ax.plot([xx,xx+0.08],[40.58,40.72], color="orangered", lw=0.8, linestyle=(0,(3,4)), zorder=3)

    for poly in [mainland, capri, ischia, procida]:
        ax.add_patch(Polygon(poly, closed=True, facecolor="#f5e67a", edgecolor="0.2", linewidth=1.8, zorder=5))
        ax.plot(poly[:,0], poly[:,1], color="black", lw=0.6, linestyle=(0,(1,2)), zorder=6)
        centroid = poly.mean(axis=0)
        scaled = centroid + (poly - centroid) * 1.035
        ax.add_patch(Polygon(scaled, closed=True, facecolor="none", edgecolor="0.45", linewidth=0.7, zorder=4))

    for name, xx, yy, fs in [("NAPOLI",14.25,40.93,16),("POZZUOLI",14.12,40.84,10),("BAGNOLI",14.17,40.81,10),("SORRENTO",14.38,40.63,10),("ISCHIA",13.86,40.75,10),("I. DI PROCIDA",14.03,40.765,9),("CAPRI",14.23,40.56,10),("GOLFO\nDI NAPOLI",14.35,40.76,11)]:
        text_outline(ax, xx, yy, name, fontsize=fs, weight="bold" if name == "NAPOLI" else "normal", ha="center", va="center", zorder=10, path_effects=[pe.withStroke(linewidth=3, foreground="#f5e67a")])
    ax.text(14.09,40.885,"UNSURVEYED", fontsize=9, zorder=10)

    for xx, yy in [(13.70,40.93),(13.78,40.88),(13.86,40.86),(14.00,40.88),(14.08,40.82),(14.24,40.78),(14.42,40.75),(14.55,40.69),(14.67,40.62),(13.74,40.58),(13.91,40.58),(14.08,40.61),(14.26,40.65),(14.41,40.52),(13.70,40.74),(14.55,40.82),(14.63,40.90)]:
        jj = int(np.argmin(np.abs(np.array(lons)-xx)))
        ii = int(np.argmin(np.abs(np.array(lats)-yy)))
        text_outline(ax, xx, yy, str(int(round(z[ii,jj]/10)*10)), ha="center", va="center", fontsize=8, color="black", zorder=7)

    for f in seamarks:
        xx, yy = f["geometry"]["coordinates"]
        if not (xmin <= xx <= xmax and ymin <= yy <= ymax):
            continue
        props = f["properties"]
        kind = props.get("kind")
        name = props.get("name", "")
        if kind == "light":
            draw_lighthouse(ax, xx, yy)
        elif kind == "buoy":
            draw_buoy(ax, xx, yy)
        elif kind in ("harbor", "marina"):
            draw_harbor(ax, xx, yy, name, marina=(kind == "marina"))
        elif kind == "anchorage":
            draw_pin(ax, xx, yy, name)

    for xx,yy,n in [(14.27,40.84,"Napoli"),(14.12,40.82,"Pozzuoli"),(14.02,40.77,"Procida"),(13.92,40.74,"Ischia"),(14.38,40.63,"Sorrento"),(14.24,40.55,"Marina Grande")]:
        draw_harbor(ax,xx,yy,n,marina=True)
    for xx,yy in [(14.26,40.82),(14.34,40.72),(14.46,40.68),(14.20,40.56),(13.91,40.80),(14.02,40.78)]:
        draw_lighthouse(ax,xx,yy)
    for xx,yy in [(14.30,40.77),(14.37,40.75),(13.97,40.78),(13.80,40.73),(14.12,40.86)]:
        draw_buoy(ax,xx,yy)
    for xx,yy,n in [(14.34,40.77,""),(14.45,40.70,""),(14.56,40.69,""),(13.73,40.66,""),(14.14,40.57,"")]:
        draw_pin(ax,xx,yy,n)

    for xx,yy in [(14.03,40.70),(14.12,40.90),(14.55,40.58),(13.94,40.86),(14.67,40.56),(13.76,40.88)]:
        text_outline(ax, xx, yy, "++", fontsize=13, zorder=7)

    bar_x0, bar_y, bar_w = 14.53, 40.515, 0.12
    ax.plot([bar_x0, bar_x0+bar_w], [bar_y, bar_y], color="black", lw=3, zorder=20)
    ax.plot([bar_x0, bar_x0], [bar_y, bar_y+0.012], color="black", lw=2, zorder=20)
    ax.plot([bar_x0+bar_w, bar_x0+bar_w], [bar_y, bar_y+0.012], color="black", lw=2, zorder=20)
    ax.text(bar_x0+bar_w/2, bar_y+0.018, "3.5", ha="center", fontsize=13, weight="bold", zorder=20)
    ax.text(bar_x0+bar_w+0.01, bar_y+0.006, "NM", ha="left", fontsize=11, zorder=20)

    ax.text(13.665, 40.492, "Experimental scientific prototype - not for navigation", fontsize=9, color="0.25", zorder=30)
    ax.set_xlim(xmin, xmax)
    ax.set_ylim(ymin, ymax)
    ax.set_aspect(1.55)
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_visible(False)

    out = ensure_dir(root / "figures")
    png = out / "tyrrhenian_east_nautical_chart_render.png"
    pdf = out / "tyrrhenian_east_nautical_chart_render.pdf"
    fig.savefig(png, dpi=200, bbox_inches="tight", pad_inches=0.02)
    fig.savefig(pdf, bbox_inches="tight", pad_inches=0.02)
    plt.close(fig)
    return [png, pdf]


def make_manifest(root: Path) -> Path:
    files = []
    for p in sorted(root.rglob("*")):
        if p.is_file():
            files.append(str(p.relative_to(root)))
    return write_json(root / "offline_bundle" / "manifest.json", {
        "name": "Tyrrhenian Open Nautical Atlas - Eastern Sector Prototype",
        "offline_first": True,
        "opencpn_compatible_layers": ["GeoJSON prototype layers; S-57/KAP/MBTiles exporters planned"],
        "signalk_resources": "offline_bundle/signalk/resources.json",
        "rendered_outputs": ["figures/tyrrhenian_east_nautical_chart_render.png", "figures/tyrrhenian_east_nautical_chart_render.pdf"],
        "cartography_ip_note": "Rendered with project-owned code and generic nautical conventions. No proprietary map tiles, icons, fonts, screenshots, or brand assets are used.",
        "fair": ["STAC metadata", "open formats", "provenance files", "reusable licenses"],
        "files": files,
    })


def zip_bundle(root: Path) -> Path:
    out = ensure_dir(root / "dist") / "tyrrhenian-east-prototype-bundle.zip"
    with zipfile.ZipFile(out, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for p in sorted(root.rglob("*")):
            if p.is_file() and "dist" not in p.relative_to(root).parts:
                zf.write(p, p.relative_to(root))
    return out
